---
deployment:
  tasks:
    - /bin/cp -R dist/assets /home/qqoophoh/vellkoerp.com/
    - /bin/cp -R dist/api /home/qqoophoh/vellkoerp.com/
    - /bin/cp -R dist/tinymce /home/qqoophoh/vellkoerp.com/
    - /bin/cp -f dist/*.html /home/qqoophoh/vellkoerp.com/
    - /bin/cp -f dist/sitemap.xml dist/robots.txt dist/site.webmanifest dist/favicon.* dist/icons.svg /home/qqoophoh/vellkoerp.com/
    - /bin/cp -f dist/.htaccess /home/qqoophoh/vellkoerp.com/.htaccess