---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qqoophoh/vellkoerp.com/
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp server.cjs $DEPLOYPATH
    - /bin/cp vite.config.js $DEPLOYPATH
    - /bin/cp .npmrc $DEPLOYPATH